import ReactDOM from 'react-dom/client'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen'

const router = createRouter({ // createRouter is a function from @tanstack/react-router that creates a new router instance  
  routeTree, // routeTree is generated by the route compiler
  defaultPreload: 'intent', // This enables preloading of route data when the user hovers over a link or focuses on it, improving perceived performance
  scrollRestoration: true, // This enables scroll restoration for all routes, where the scroll position is restored when navigating back to a previous route
})

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

const rootElement = document.getElementById('app')!

if (!rootElement.innerHTML) {
  const root = ReactDOM.createRoot(rootElement)
  root.render(<RouterProvider router={router} />)
}
