import { createRouter as createTanStackRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen'

export function getRouter() {
// createTanStackRouter is a function from @tanstack/react-router
// that creates a new router instance,
// createTanStackRouter VS createRouter: The difference between
// createTanStackRouter and createRouter is that createTanStackRouter is 
// the original function from @tanstack/react-router, while createRouter
// is a wrapper function that adds additional functionality or customization to the router instance. In this case, createRouter is used to set defaultPreloadStaleTime to 0, which means that preloaded data will be considered stale immediately and will be refetched on the next navigation.
  const router = createTanStackRouter({ 
    routeTree, // routeTree is generated by the route compiler
    scrollRestoration: true, // This enables scroll restoration for all routes, where the scroll position is restored when navigating back to a previous route
    defaultPreload: 'intent', // This enables preloading of route data when the user hovers over a link or focuses on it, improving perceived performance
    defaultPreloadStaleTime: 0, // This sets the default stale time for preloaded data to 0, meaning that preloaded data will be considered stale immediately and will be refetched on the next navigation
  })

  return router
}

declare module '@tanstack/react-router' {
  interface Register {
    router: ReturnType<typeof getRouter>
  }
}
