/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MoreRouteImport } from './routes/more'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YoutubeProfileIndexRouteImport } from './routes/youtube/profile/index'
import { Route as YoutubeProfileMusabRouteImport } from './routes/youtube/profile/musab'
import { Route as YoutubeProfileFahadRouteImport } from './routes/youtube/profile/fahad'

const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeProfileIndexRoute = YoutubeProfileIndexRouteImport.update({
  id: '/youtube/profile/',
  path: '/youtube/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeProfileMusabRoute = YoutubeProfileMusabRouteImport.update({
  id: '/youtube/profile/musab',
  path: '/youtube/profile/musab',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeProfileFahadRoute = YoutubeProfileFahadRouteImport.update({
  id: '/youtube/profile/fahad',
  path: '/youtube/profile/fahad',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/home': typeof HomeRoute
  '/more': typeof MoreRoute
  '/youtube/profile/fahad': typeof YoutubeProfileFahadRoute
  '/youtube/profile/musab': typeof YoutubeProfileMusabRoute
  '/youtube/profile/': typeof YoutubeProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/home': typeof HomeRoute
  '/more': typeof MoreRoute
  '/youtube/profile/fahad': typeof YoutubeProfileFahadRoute
  '/youtube/profile/musab': typeof YoutubeProfileMusabRoute
  '/youtube/profile': typeof YoutubeProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/home': typeof HomeRoute
  '/more': typeof MoreRoute
  '/youtube/profile/fahad': typeof YoutubeProfileFahadRoute
  '/youtube/profile/musab': typeof YoutubeProfileMusabRoute
  '/youtube/profile/': typeof YoutubeProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/home'
    | '/more'
    | '/youtube/profile/fahad'
    | '/youtube/profile/musab'
    | '/youtube/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/home'
    | '/more'
    | '/youtube/profile/fahad'
    | '/youtube/profile/musab'
    | '/youtube/profile'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/home'
    | '/more'
    | '/youtube/profile/fahad'
    | '/youtube/profile/musab'
    | '/youtube/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HomeRoute: typeof HomeRoute
  MoreRoute: typeof MoreRoute
  YoutubeProfileFahadRoute: typeof YoutubeProfileFahadRoute
  YoutubeProfileMusabRoute: typeof YoutubeProfileMusabRoute
  YoutubeProfileIndexRoute: typeof YoutubeProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube/profile/': {
      id: '/youtube/profile/'
      path: '/youtube/profile'
      fullPath: '/youtube/profile/'
      preLoaderRoute: typeof YoutubeProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube/profile/musab': {
      id: '/youtube/profile/musab'
      path: '/youtube/profile/musab'
      fullPath: '/youtube/profile/musab'
      preLoaderRoute: typeof YoutubeProfileMusabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube/profile/fahad': {
      id: '/youtube/profile/fahad'
      path: '/youtube/profile/fahad'
      fullPath: '/youtube/profile/fahad'
      preLoaderRoute: typeof YoutubeProfileFahadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HomeRoute: HomeRoute,
  MoreRoute: MoreRoute,
  YoutubeProfileFahadRoute: YoutubeProfileFahadRoute,
  YoutubeProfileMusabRoute: YoutubeProfileMusabRoute,
  YoutubeProfileIndexRoute: YoutubeProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
