/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlowPostsRouteImport } from './routes/slowPosts'
import { Route as MoreRouteImport } from './routes/more'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YoutubeIndexRouteImport } from './routes/youtube/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'
import { Route as YoutubeProfileRouteRouteImport } from './routes/youtube/profile/route'
import { Route as YoutubeProfileIndexRouteImport } from './routes/youtube/profile/index'
import { Route as YoutubeProfileMusabRouteImport } from './routes/youtube/profile/musab'
import { Route as YoutubeProfileFahadRouteImport } from './routes/youtube/profile/fahad'

const SlowPostsRoute = SlowPostsRouteImport.update({
  id: '/slowPosts',
  path: '/slowPosts',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeIndexRoute = YoutubeIndexRouteImport.update({
  id: '/youtube/',
  path: '/youtube/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeProfileRouteRoute = YoutubeProfileRouteRouteImport.update({
  id: '/youtube/profile',
  path: '/youtube/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeProfileIndexRoute = YoutubeProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => YoutubeProfileRouteRoute,
} as any)
const YoutubeProfileMusabRoute = YoutubeProfileMusabRouteImport.update({
  id: '/musab',
  path: '/musab',
  getParentRoute: () => YoutubeProfileRouteRoute,
} as any)
const YoutubeProfileFahadRoute = YoutubeProfileFahadRouteImport.update({
  id: '/fahad',
  path: '/fahad',
  getParentRoute: () => YoutubeProfileRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/home': typeof HomeRoute
  '/more': typeof MoreRoute
  '/slowPosts': typeof SlowPostsRoute
  '/youtube/profile': typeof YoutubeProfileRouteRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/': typeof PostsIndexRoute
  '/youtube/': typeof YoutubeIndexRoute
  '/youtube/profile/fahad': typeof YoutubeProfileFahadRoute
  '/youtube/profile/musab': typeof YoutubeProfileMusabRoute
  '/youtube/profile/': typeof YoutubeProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/home': typeof HomeRoute
  '/more': typeof MoreRoute
  '/slowPosts': typeof SlowPostsRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts': typeof PostsIndexRoute
  '/youtube': typeof YoutubeIndexRoute
  '/youtube/profile/fahad': typeof YoutubeProfileFahadRoute
  '/youtube/profile/musab': typeof YoutubeProfileMusabRoute
  '/youtube/profile': typeof YoutubeProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/home': typeof HomeRoute
  '/more': typeof MoreRoute
  '/slowPosts': typeof SlowPostsRoute
  '/youtube/profile': typeof YoutubeProfileRouteRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/': typeof PostsIndexRoute
  '/youtube/': typeof YoutubeIndexRoute
  '/youtube/profile/fahad': typeof YoutubeProfileFahadRoute
  '/youtube/profile/musab': typeof YoutubeProfileMusabRoute
  '/youtube/profile/': typeof YoutubeProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/home'
    | '/more'
    | '/slowPosts'
    | '/youtube/profile'
    | '/posts/$postId'
    | '/posts/'
    | '/youtube/'
    | '/youtube/profile/fahad'
    | '/youtube/profile/musab'
    | '/youtube/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/home'
    | '/more'
    | '/slowPosts'
    | '/posts/$postId'
    | '/posts'
    | '/youtube'
    | '/youtube/profile/fahad'
    | '/youtube/profile/musab'
    | '/youtube/profile'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/home'
    | '/more'
    | '/slowPosts'
    | '/youtube/profile'
    | '/posts/$postId'
    | '/posts/'
    | '/youtube/'
    | '/youtube/profile/fahad'
    | '/youtube/profile/musab'
    | '/youtube/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HomeRoute: typeof HomeRoute
  MoreRoute: typeof MoreRoute
  SlowPostsRoute: typeof SlowPostsRoute
  YoutubeProfileRouteRoute: typeof YoutubeProfileRouteRouteWithChildren
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
  YoutubeIndexRoute: typeof YoutubeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/slowPosts': {
      id: '/slowPosts'
      path: '/slowPosts'
      fullPath: '/slowPosts'
      preLoaderRoute: typeof SlowPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube/': {
      id: '/youtube/'
      path: '/youtube'
      fullPath: '/youtube/'
      preLoaderRoute: typeof YoutubeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube/profile': {
      id: '/youtube/profile'
      path: '/youtube/profile'
      fullPath: '/youtube/profile'
      preLoaderRoute: typeof YoutubeProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube/profile/': {
      id: '/youtube/profile/'
      path: '/'
      fullPath: '/youtube/profile/'
      preLoaderRoute: typeof YoutubeProfileIndexRouteImport
      parentRoute: typeof YoutubeProfileRouteRoute
    }
    '/youtube/profile/musab': {
      id: '/youtube/profile/musab'
      path: '/musab'
      fullPath: '/youtube/profile/musab'
      preLoaderRoute: typeof YoutubeProfileMusabRouteImport
      parentRoute: typeof YoutubeProfileRouteRoute
    }
    '/youtube/profile/fahad': {
      id: '/youtube/profile/fahad'
      path: '/fahad'
      fullPath: '/youtube/profile/fahad'
      preLoaderRoute: typeof YoutubeProfileFahadRouteImport
      parentRoute: typeof YoutubeProfileRouteRoute
    }
  }
}

interface YoutubeProfileRouteRouteChildren {
  YoutubeProfileFahadRoute: typeof YoutubeProfileFahadRoute
  YoutubeProfileMusabRoute: typeof YoutubeProfileMusabRoute
  YoutubeProfileIndexRoute: typeof YoutubeProfileIndexRoute
}

const YoutubeProfileRouteRouteChildren: YoutubeProfileRouteRouteChildren = {
  YoutubeProfileFahadRoute: YoutubeProfileFahadRoute,
  YoutubeProfileMusabRoute: YoutubeProfileMusabRoute,
  YoutubeProfileIndexRoute: YoutubeProfileIndexRoute,
}

const YoutubeProfileRouteRouteWithChildren =
  YoutubeProfileRouteRoute._addFileChildren(YoutubeProfileRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HomeRoute: HomeRoute,
  MoreRoute: MoreRoute,
  SlowPostsRoute: SlowPostsRoute,
  YoutubeProfileRouteRoute: YoutubeProfileRouteRouteWithChildren,
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
  YoutubeIndexRoute: YoutubeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
